project:
  output-dir: _site
  render:
    - "*.qmd"

#toc: true
#number-sections: true
  
format: 
  revealjs:
    scrollable: true
    margin: 0
    code-overflow: wrap
    reference-location: document
    widescreen: true
    center: true
    transition: slide
    theme: [night, style.css]
    self_contained: false
    footer: "<img src='logo-cornell.png' style='height: 2em;'>"
    reveal_options:
        slideNumber: true
        previewLinks: false
        chalkboard:
          theme: chalkboard
          toggleNotesButton: true
    reveal_plugins: ["chalkboard"]


